module.exports = [
  'react',
  'prop-types',
  'react-dom',
  'react-emotion',
  'react-helmet',
  'mobx',
  'mobx-state-tree',
  'mobx-react',
  'worona-deps',
  'superagent',
  'styled-components',
  'redux',
  'redux-saga',
  'reselect',
  'react-redux',
  'recompose',
];
